spring:
  application:
    name: mybatis-plus
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver


server:
  port: 8888
